name: Tweet Automation

on:
  schedule:
    - cron: '30 2 * * *'  # 8 AM IST
    - cron: '30 14 * * *' # 8 PM IST
  workflow_dispatch:

jobs:
  tweet:
    runs-on: ubuntu-latest

    env:
      API_KEY: ${{ secrets.API_KEY }}
      API_SECRET: ${{ secrets.API_SECRET }}
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tweepy requests

    - name: Run tweet script
      run: python x.py
