name: Tweet Supabase 3

on:
  schedule:
    - cron: '30 2 * * *'   # 8 AM IST
    - cron: '30 8 * * *'   # 2 PM IST
    - cron: '30 14 * * *'  # 8 PM IST
  workflow_dispatch:

jobs:
  tweet:
    runs-on: ubuntu-latest

    env:
      API_KEY: ${{ secrets.API_KEY }}
      API_SECRET: ${{ secrets.API_SECRET }}
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Updated to latest version

      - name: Setup Python
        uses: actions/setup-python@v5  # Updated to latest version
        with:
          python-version: '3.10'  # Explicitly specify a supported version
          cache: 'pip'  # Cache pip dependencies for faster runs

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tweet Automation
        run: python x.py
